AWSTemplateFormatVersion: '2010-09-09'
Description: The AWS CloudFormation template for EDS Daily Digest

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - qa
    - prod
  
  BucketName:
    Type: String
    Default: eds-cf-templates

  Stack:
    Type: String
    Default: eds-daily-digest

  RepoOwner:
    Type: String
    Default: EquityDataScience

  RepoName:
    Type: String
    Default: eds-daily-digest

  RepoBranch:
    Type: String
    Default: dev


  ComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE
    Description: "BUILD_GENERAL1_SMALL: Use up to 3 GB memory and 2 vCPUs for builds. BUILD_GENERAL1_MEDIUM: Use up to 7 GB memory and 4 vCPUs for builds. BUILD_GENERAL1_LARGE: Use up to 15 GB memory and 8 vCPUs for builds."

  PrivateSubnets:
    Description: VPC Private PrivateSubnets
    Type: AWS::SSM::Parameter::Value<List<String>>
    Default: /vpc/private_subnets
    
  VPCID:
    Description: Master VPC ID
    Type : AWS::SSM::Parameter::Value<String>
    Default: /vpc/vpcid

Resources:
  LambdaStepfunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/${Stage}/eds-daily-digest/templates/eds-daily-digest-app.yaml'
      Parameters:
        VPCID: !Ref VPCID
        PrivateSubnets: !Join
          - ','
          - !Ref PrivateSubnets
        Stage: !Ref Stage
        Stack: !Ref Stack

  CodePipeLine:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/${Stage}/eds-daily-digest/templates/eds-daily-digest-code-pipeline.yaml'
      Parameters:
        Stage: !Ref Stage
        Stack: !Ref Stack
        ComputeType: !Ref ComputeType
        RepoOwner: !Ref RepoOwner
        RepoName: !Ref RepoName
        RepoBranch: !Ref RepoBranch
        TriggerLambda: !GetAtt LambdaStepfunctions.Outputs.TriggerLambda
        ExecutorLambda: !GetAtt LambdaStepfunctions.Outputs.ExecutorLambda
